# Generated by Django 5.1 on 2024-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Clothing', 'Clothing'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Housing', 'Housing'), ('Music', 'Music'), ('Social', 'Social'), ('Other', 'Other')], max_length=100)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
